/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.13/samples
 */

plugins {
java
application
}

group = "org.example"
version = "1.0"

repositories {
mavenCentral()
}

application {
mainClass.set("Main");
}
tasks.named<Test>("test"){
    enabled = false
}

tasks.jar {
    manifest{
        attributes["Main-Class"] = "Main"
    }
}
