/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        MathOperations mo = new MathOperations();
        System.out.println("Add 5 + 3" + mo.add(5,3));   
        System.out.println("Minus 5 - 3" + mo.minus(5,3));
        System.out.println("Mnozh 5 * 3" + mo.multiply(5,3));


    }

}
